title: Bored cats
description: Here you can find many cool games and interesting facts.
permalink: ':title/'
baseurl: "/" 
url: "https://boredcats.github.io" 
site-twitter: 


author: Bored cats  
author-img: logo-pie.png  
about-author: If you´re bored this blog will be of use.
social-twitter: 
social-facebook: 
social-github: 
social-linkedin: 
social-email: 




# Disqus
discus-identifier:  

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
